YAML save file implementation along with other fixes
Ben1152000/sootty pull request #51
Opened 2022-07-27 08:36 UTC by KarthikL1729

2022-07-27 08:37 UTC, KarthikL1729 commented
Issues #48 and #47 fixed with this PR.

2022-08-02 07:39 UTC, Ben1152000 requested changes
Just a couple of small fixes to the implementation.

2022-08-02 07:39 UTC, Ben1152000 commented on sootty/__main__.py
>      compile(
This appears to be a reserved name in python3.x, maybe change it to `compile_query`.

2022-08-02 07:39 UTC, Ben1152000 commented on sootty/save.py
> +        cmd += ' -f "' + name + '"'
Python string formatting would be helpful here, since it automatically converts the variable to the correct type:

```f' -f "{name}"'```

2022-08-24 15:31 UTC, Ben1152000 approved these changes

2022-08-24 15:33 UTC, merged